apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gcp-gke-template-create-v3
  title: GCP - GKE (Kubernetes) - Create - V3
  description: Create a GKE (Kubernetes) cluster in GCP
  tags:
    - infra
    - terraform
    - gcp
    - gke
spec:
  owner: group:infraops
  type: kubernetes

  parameters:
    - title: About
      required:
        - component_id
      properties:
        component_id:
          title: Name
          type: string
          description: The unique name of the cluster
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Description of the cluster

    - title: Ownership
      required:
        - organisation
        - owner
      properties:
        organisation:
          title: Organisation
          type: string
          description: GitHub Organisation where this will live
          enum:
            - spotify-portal-public-demo
        owner:
          title: Owner
          type: string
          description: Owner of the cluster
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              - kind: Group

    - title: Configuration
      required:
        - region
      properties:
        region:
          title: GCP Region
          type: string
          description: GCP region of the cluster
          enum:
            - europe-west1
            - us-central1
            - asia-east1

  steps:
    - id: template
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values: &parameters
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          organisation: ${{ parameters.organisation }}
          owner: ${{ parameters.owner }}
          region: ${{ parameters.region }}

    - id: convert_params
      name: Convert Parameters
      action: roadiehq:utils:serialize:json
      input:
        data: *parameters

    - id: write_params
      name: Write Params
      action: roadiehq:utils:fs:write
      input:
        path: .template.json
        content: ${{ steps.convert_params.output.serialized }}

    - id: create_catalog
      name: Create Catalog File
      action: catalog:write
      input:
        entity:
          apiVersion: backstage.io/v1alpha1
          kind: Resource
          metadata:
            name: ${{ parameters.component_id }}
            description: ${{ parameters.description | dump }}
            tags:
              - gcp
              - gke
            annotations:
              backstage.io/techdocs-ref: dir:.
              github.com/project-slug: ${{ parameters.organisation }}/${{ parameters.component_id }}
          spec:
            type: kubernetes
            lifecycle: experimental
            owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        repoUrl: github.com?owner=${{ parameters.organisation }}&repo=${{ parameters.component_id }}
        description: This is ${{ parameters.component_id }}
        repoVisibility: public
        defaultBranch: main
        protectEnforceAdmins: false

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
    text:
      - title: Connecting to your cluster
        content: |-
          To connect to your new GKE cluster, run the below command:
          ```
          gcloud container clusters get-credentials ${{ parameters.component_id }} --region ${{ parameters.region }} --project spotify-portal-public-demo
          ```

          Note: it will take a few minutes for your cluster to be ready.
