apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gcp-gke-template-update-v3
  title: GCP - GKE (Kubernetes) - Update - V3
  description: Update a GKE (Kubernetes) cluster in GCP
  tags:
    - infra
    - terraform
    - gcp
    - gke
spec:
  owner: group:infraops
  type: kubernetes

  steps:
    - id: get_entities
      name: Get Entities
      action: catalog:query:plus
      input:
        queries:
          - limit: 10
            filter:
              metadata.annotations.backstage.io/source-template: template:default/gcp-gke-template-create

    - id: fetch_entities
      name: Fetch Entity
      action: fetch:plain
      each: ${{ steps.get_entities.output.results[0] }}
      input:
        url: ${{ each.value.metadata.annotations['backstage.io/source-location'] | replace('url:', '') }}
        targetPath: ${{ each.value.metadata.name }}

    - id: read_params
      name: Read Params
      action: roadiehq:utils:fs:parse
      each: ${{ steps.get_entities.output.results[0] }}
      input:
        path: ${{ each.value.metadata.name }}/.template.json
        parser: json

    - id: debug2
      name: Debug
      action: debug:log
      input:
        message: ${{ steps.read_params | dump }}

    - id: template
      name: Fetch Skeleton
      action: fetch:template
      each: ${{ steps.get_entities.output.results[0] }}
      input:
        url: ${{ each.value.metadata.name }}/skeleton
        replace: true
        values: ${{ steps.read_params.outputs[each.key].content }}
        targetPath: ${{ each.value.metadata.name }}

    - id: update_pr
      name: Update PR
      action: publish:github:pull-request
      each: ${{ steps.get_entities.output.results[0] }}
      input:
        repoUrl: github.com?owner=${{ steps.read_params.outputs[each.key].content.organisation }}&repo=${{ steps.read_params.outputs[each.key].content.component_id }}
        branchName: update-from-template
        title: update from template
        description: This PR updates the entity with the latest version
        update: true
        sourcePath: ${{ each.value.metadata.name }}

  # TODO: try to not send PR if there are no changes, then log message in output

  output:
    text:
      - title: PRs Created
        content: |
          All PRs were created... (TODO: show count)
    # links:
    #   - title: Update PR
    #     url: ${{ steps.update_pr.output.remoteUrl }}
